In [ ]:
!wget https://zenodo.org/records/1203745/files/UrbanSound8K.tar.gz

--2024-02-03 11:08:04--  https://zenodo.org/records/1203745/files/UrbanSound8K.tar.gz
Resolving zenodo.org (zenodo.org)... 188.185.79.172, 188.184.103.159, 188.184.98.238, ...
Connecting to zenodo.org (zenodo.org)|188.185.79.172|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 6023741708 (5.6G) [application/octet-stream]
Saving to: ‘UrbanSound8K.tar.gz’

UrbanSound8K.tar.gz 100%[===================>]   5.61G  20.3MB/s    in 4m 51s  

2024-02-03 11:12:56 (19.7 MB/s) - ‘UrbanSound8K.tar.gz’ saved [6023741708/6023741708]



In [ ]:
import shutil
shutil.unpack_archive("/content/UrbanSound8K.tar.gz")

ERROR: Could not find a version that satisfies the requirement shutil (from versions: none)
ERROR: No matching distribution found for shutil


In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
!cp "/content/UrbanSound8K.tar.gz" "/content/drive/MyDrive/learn_audio-classification"

In [ ]:
!pip install librosa

In [ ]:
import librosa
audio_data, sample_rate = librosa.load('/content/UrbanSound8K/audio/fold1/101415-3-0-2.wav')

In [ ]:
audio_data, audio_data.shape

(array([-0.00011485, -0.00017083, -0.00017736, ..., -0.04609928,
        -0.04609471, -0.05099387], dtype=float32),
 (88200,))

In [ ]:
sample_rate

22050

In [ ]:
audio_data, sample_rate = librosa.load('/content/UrbanSound8K/audio/fold1/102842-3-1-0.wav')

In [ ]:
audio_data, audio_data.shape, sample_rate

(array([ 0.00742023,  0.00979148,  0.00830646, ..., -0.00846579,
        -0.00804312, -0.01079349], dtype=float32),
 (88200,),
 22050)

In [ ]:
# extract features using mfcc youtube link : https://www.youtube.com/watch?v=4_SH2nfbQZ8&t=0s

mfccs = librosa.feature.mfcc(y = audio_data, sr = sample_rate, n_mfcc=40)
mfccs, mfccs.shape

(array([[-4.01266266e+02, -3.82031769e+02, -3.80995331e+02, ...,
         -3.69469574e+02, -3.67088440e+02, -3.75428650e+02],
        [ 1.07394882e+02,  1.04264328e+02,  1.03939728e+02, ...,
          1.19616837e+02,  1.21089195e+02,  1.19483215e+02],
        [ 2.77272949e+01,  3.01472588e+01,  2.91092873e+01, ...,
          3.78709564e+01,  3.66863251e+01,  3.36934967e+01],
        ...,
        [ 1.23870111e+00,  1.71230364e+00,  3.31807733e+00, ...,
         -2.06129551e-02, -1.50218201e+00, -2.72790241e+00],
        [-6.64531422e+00, -8.02330971e+00, -3.92108512e+00, ...,
         -7.82035923e+00, -2.50892448e+00,  1.21789062e+00],
        [-1.85728657e+00, -5.17095995e+00, -6.44906282e+00, ...,
         -6.26367331e+00, -2.58269620e+00, -1.30357456e+00]], dtype=float32),
 (40, 173))

In [ ]:
import pandas as pd
import numpy as np
import librosa

In [ ]:
# import numpy as np
# np.mean(np.array([[1,2],[3,4]]).T, axis = 0)

array([1.5, 3.5])

In [ ]:
csv_path = '/content/UrbanSound8K/metadata/UrbanSound8K.csv'
audio_path = '/content/UrbanSound8K/audio/'
dataset = pd.read_csv(csv_path)
dataset.head()

slice_file_name    fsID  start        end  salience  fold  classID  \
0    100032-3-0-0.wav  100032    0.0   0.317551         1     5        3   
1  100263-2-0-117.wav  100263   58.5  62.500000         1     5        2   
2  100263-2-0-121.wav  100263   60.5  64.500000         1     5        2   
3  100263-2-0-126.wav  100263   63.0  67.000000         1     5        2   
4  100263-2-0-137.wav  100263   68.5  72.500000         1     5        2   

              class  
0          dog_bark  
1  children_playing  
2  children_playing  
3  children_playing  
4  children_playing

In [ ]:
def extract_features(file_address):
  audio_data, sample_rate = librosa.load(file_address)
  mfcc_feature = librosa.feature.mfcc(y = audio_data, sr = sample_rate, n_mfcc=40)
  return np.mean(mfcc_feature.T, axis = 0), mfcc_feature


In [ ]:
x_mfcc, x_mfcc_mean = [], []
for i in range(0, len(dataset['slice_file_name'])):
  folder = f"fold{dataset['fold'][i]}"
  file_address = f"{audio_path}{folder}/{dataset['slice_file_name'][i]}"
  mfcc_feature_mean, mfcc_feature = extract_features(file_address)
  x_mfcc.append(mfcc_feature)
  x_mfcc_mean.append(mfcc_feature_mean)

len(x_mfcc), len(x_mfcc_mean)
# x_mfcc = np.array(x_mfcc)
# x_mfcc_mean = np.array(x_mfcc_mean)

# x_mfcc_mean.shape, x_mfcc.shape

/usr/local/lib/python3.10/dist-packages/librosa/core/spectrum.py:257: UserWarning: n_fft=2048 is too large for input signal of length=1323
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/librosa/core/spectrum.py:257: UserWarning: n_fft=2048 is too large for input signal of length=1103
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/librosa/core/spectrum.py:257: UserWarning: n_fft=2048 is too large for input signal of length=1523
  warnings.warn(


(8732, 8732)

In [ ]:
feature_dataframe = pd.DataFrame({"mfcc" : x_mfcc, "mfcc_mean" : x_mfcc_mean, "classid" :  dataset['classID'], 'audio_name' : dataset['slice_file_name'], 'class_name' : dataset["class"]})
y = dataset['classID']

In [ ]:
feature_dataframe

mfcc  \
0     [[-332.0388, -169.58775, -90.246826, -56.92347...   
1     [[-486.0561, -447.30463, -441.84772, -436.2216...   
2     [[-492.76328, -465.86954, -473.96152, -480.512...   
3     [[-441.2638, -405.2567, -401.20792, -400.8395,...   
4     [[-467.48068, -431.21393, -435.46893, -434.359...   
...                                                 ...   
8727  [[-424.15533, -396.181, -399.4792, -400.9147, ...   
8728  [[-479.0948, -449.7615, -445.87476, -440.4198,...   
8729  [[-322.78165, -295.09012, -297.30344, -295.924...   
8730  [[-398.03085, -364.12985, -359.62103, -357.777...   
8731  [[-336.01422, -302.89465, -299.18787, -299.343...   

                                              mfcc_mean  classid  \
0     [-211.93698, 62.581215, -122.813156, -60.74529...        3   
1     [-417.0052, 99.336624, -42.995586, 51.073326, ...        2   
2     [-452.39316, 112.36253, -37.578075, 43.195866,...        2   
3     [-406.47922, 91.1966, -25.043556, 42.78452, 11...        2   
4     [-439.63873, 103.86223, -42.658787, 50.690285,...        2   
...                                                 ...      ...   
8727  [-391.3721, 125.36239, -40.634056, 25.899754, ...        1   
8728  [-339.42715, 76.409096, -35.30988, 41.984035, ...        1   
8729  [-297.31534, 102.09026, -36.75108, 26.816488, ...        1   
8730  [-336.92386, 115.3139, -44.84709, 24.968985, -...        1   
8731  [-307.41763, 83.306725, -25.756512, 35.44811, ...        1   

              audio_name        class_name  
0       100032-3-0-0.wav          dog_bark  
1     100263-2-0-117.wav  children_playing  
2     100263-2-0-121.wav  children_playing  
3     100263-2-0-126.wav  children_playing  
4     100263-2-0-137.wav  children_playing  
...                  ...               ...  
8727     99812-1-2-0.wav          car_horn  
8728     99812-1-3-0.wav          car_horn  
8729     99812-1-4-0.wav          car_horn  
8730     99812-1-5-0.wav          car_horn  
8731     99812-1-6-0.wav          car_horn  

[8732 rows x 5 columns]

In [ ]:
feature_dataframe.to_csv('final_dataframe.csv')

In [ ]:
project_path = '/content/drive/MyDrive/learn_audio-classification'

!cp '/content/final_dataframe.csv' '/content/drive/MyDrive/learn_audio-classification'

In [ ]:
x_mfcc_mean_array = np.array(x_mfcc_mean)
x_mfcc_mean_array.shape

(8732, 40)

In [49]:
from sklearn.model_selection import train_test_split
from tensorflow.keras.utils import to_categorical

In [50]:
y = to_categorical(y)
y.shape

(8732, 10)

In [51]:
x_train, x_test, y_train, y_test = train_test_split(x_mfcc_mean_array, y, test_size=0.2, random_state=0)

In [56]:
feature_dataframe['class_name'].value_counts()

dog_bark            1000
children_playing    1000
air_conditioner     1000
street_music        1000
engine_idling       1000
jackhammer          1000
drilling            1000
siren                929
car_horn             429
gun_shot             374
Name: class_name, dtype: int64

In [57]:
x_train.shape, x_test.shape, y_train.shape, y_test.shape

((6985, 40), (1747, 40), (6985, 10), (1747, 10))

In [63]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.callbacks import EarlyStopping

callback = EarlyStopping(monitor='val_accuracy', patience=4)

model = Sequential()
model.add(Dense(1000, input_shape = (40,)))
model.add(Dense(500, activation = 'relu'))
model.add(Dense(100, activation = 'relu'))
model.add(Dense(10, activation = 'softmax'))

model.compile(loss="categorical_crossentropy", optimizer="adam", metrics=["accuracy"])


In [64]:
history = model.fit(x_train, y_train, batch_size = 100, epochs = 100, validation_split = 0.2, callbacks=[callback])

Epoch 1/100
56/56 [==============================] - 3s 26ms/step - loss: 5.7808 - accuracy: 0.3357 - val_loss: 1.6008 - val_accuracy: 0.5118
Epoch 2/100
56/56 [==============================] - 1s 18ms/step - loss: 1.4711 - accuracy: 0.5395 - val_loss: 1.3943 - val_accuracy: 0.5648
Epoch 3/100
56/56 [==============================] - 1s 18ms/step - loss: 1.4253 - accuracy: 0.5526 - val_loss: 1.4432 - val_accuracy: 0.5218
Epoch 4/100
56/56 [==============================] - 1s 17ms/step - loss: 1.2546 - accuracy: 0.5947 - val_loss: 1.2306 - val_accuracy: 0.6092
Epoch 5/100
56/56 [==============================] - 1s 17ms/step - loss: 1.1259 - accuracy: 0.6380 - val_loss: 1.1371 - val_accuracy: 0.6342
Epoch 6/100
56/56 [==============================] - 1s 17ms/step - loss: 1.0608 - accuracy: 0.6621 - val_loss: 1.2672 - val_accuracy: 0.5991
Epoch 7/100
56/56 [==============================] - 1s 18ms/step - loss: 1.0024 - accuracy: 0.6756 - val_loss: 1.1001 - val_accuracy: 0.6557
Epoch 

In [65]:
test_loss, test_acc = model.evaluate(x_test, y_test)
print("Test accuracy:", test_acc)

55/55 [==============================] - 0s 6ms/step - loss: 0.6287 - accuracy: 0.8449
Test accuracy: 0.8448769450187683
